### PR TITLE
Fixes issue #1 Service[redis-server] cannot run /etc/init.d/redis_6379

### PR DESCRIPTION
**Pull request by rhec**

### CODE REVIEW

**Comment by rhec** [comment]
fixes issue #1
Sorry I couldn't figure out how to directly attach the pull request to that issue. I thought it might parse it out of the title, but no luck.

**Comment by joefiorini** [comment]
@thomasvandoren Is there anything keeping you from pulling this in? I'm seeing the same issue and would rather not have to use a fork.

**Comment by thomasvandoren** [comment]
Oops, I had my github notifications turned off. Sorry about the delayed response.

**Comment by thomasvandoren** [comment]
Thanks for the pull request @rhec. I posted a [new release](https://forge.puppetlabs.com/users/thomasvandoren/modules/redis) on puppet forge with the fix.

**Pull request merged**
