### PR TITLE
Allow configuration parameters to be applied to default server.

### PR DESCRIPTION
**Pull request by brucem**
This pull request add the redis::instance parameters to the default class so the default instance can be configured.

### CODE REVIEW

**Comment by criemen** [comment]
Please include this, we need to restrict the host redis runs on in all configurations, because our servers are accesible from the internet - we don't want to expose a running redis instance to everyone.
I've tested this and it works great :)

**Comment by leafac** [comment]
:+1:

I need this too.

**Comment by gcmalloc** [comment]
:+1: 
same thing here

**Comment by leafac** [comment]
:heart:

**Comment by brucem** [comment]
Thanks!

**Pull request merged**
