### PR TITLE
Fix download url

### PR DESCRIPTION
**Pull request by coffeejunk**
Since the packages are not available on `http://redis.googlecode.com/files/$pkg_name` anymore, I changed the download URL to `http://download.redis.io/releases/$pkg_name`

I also added version numbers to the dependencies in the Modulefile. This is necessary if you are a user of librarian-puppet and the issue rodjek/librarian-puppet#94 remains unaddressed.

### CODE REVIEW

**Comment by cyrusstoller** [comment]
+1

**Comment by natewarr** [comment]
+1

**Comment by spuder** [comment]
Is this puppet module dead? This merge request has been open for a while.

**Comment by cyrusstoller** [comment]
@spuder I've been wondering the same thing.

**Pull request merged**
