### PR TITLE
Fix for variable access waring in Puppet 3.2

### PR DESCRIPTION
**Pull request by dol**
Since Puppet version 3.2, allot of warnings are shown while using the redis module.

`Warning: Variable access via 'redis_port' is deprecated. Use '@redis_port' instead`

This fix this, Puppetlabs recommends to use a @-[prefix](http://docs.puppetlabs.com/guides/templating.html#referencing-variables).

Also removed some not needed trailing white spaces.

### CODE REVIEW

**Comment by leafac** [comment]
Awesome! I want to get rid of those warnings too.

**Comment by cyrusstoller** [comment]
+1

**Comment by tizzo** [comment]
+1

**Comment by thomasvandoren** [comment]
Fixed in #31 .

**Comment by tizzo** [comment]
Woooooooooooooooooooooooooooooooooooooooooooh!!!!! So happy to see this!

**Pull request closed without merging**
