### PR TITLE
Fix module to use with Librarian Puppet in newer versions of Puppet

### PR DESCRIPTION
**Pull request by leafac**
This PR fixes three unrelated issues. If you'd like I could split them in three different PRs.

### CODE REVIEW

**Comment by mjward** [comment]
The dependency versions in the Modulefile need to be set otherwise librarian-puppet throws errors.
To make this module useful moving forward can we get this PR merged in please?

**Comment by arnaudbreton** [comment]
Just get into this issue, not able to load this modulee through Librarian via Puppet. Please merge this PR..

**Comment by anovitskiy** [comment]
according to documentation on [Dependencies in the Modulefile](http://docs.puppetlabs.com/puppet/3/reference/modules_publishing.html#dependencies-in-the-modulefile), dependency versions must be specified using >= instead of ~>

**Comment by leafac** [comment]
@anovitskiy, actually the intended behavior would be to use `1.2.x` instead of the `>=` operator. I can make the change, if you'd like, but this PR is stale, anyways.

**Comment by thomasvandoren** [comment]
The template and dependency versions have been fixed on master. The class exists mostly for backwards compatibility, so I would prefer not to expose the new defines parameters in the class.

**Comment by thomasvandoren** [comment]
It seems people wanted to use the instance parameters on the class, so that functionality is also now in master. Closing this pull request. Thanks!

**Comment by leafac** [comment]
:+1:

**Pull request closed without merging**
