### PR TITLE
Adding ability to parameterize snapshotting

### PR DESCRIPTION
**Pull request by kjoconnor**

### CODE REVIEW

**Comment by criemen** [comment]
:+1:
This would be really great, we need to tune this parameter as our redis instance has lots of keys

**Comment by criemen** [comment]
But could it be that you forgot to include params.pp?

**Comment by kjoconnor** [comment]
Added - thanks @Corni !

**Comment by kjoconnor** [comment]
Any update here?

**Comment by kjoconnor** [comment]
I can fix this branch, but would it ever be merged @thomasvandoren ?

**Comment by thomasvandoren** [comment]
I am planning to release a new version this month. I would like to include this pr. I tried to add some spec tests, but timed out. If you can add a couple tests that exercise the new saves config, I would be happy to merge it! The branch I was working off of is: https://github.com/thomasvandoren/puppet-redis/tree/config-saves

**Comment by kjoconnor** [comment]
Unfortunately I'm not too well versed in Puppet testing, if this being merged is dependent on me adding those I'll try and learn, but I probably won't be able to get to it for a week or two.  If anyone else wants to add it please feel free to go ahead with this!

**Comment by thomasvandoren** [comment]
I added a couple tests and merged. Thanks!

**Pull request merged**
