### PR TITLE
Fixed issue #12

### PR DESCRIPTION
**Pull request by antonbabenko**

### CODE REVIEW

**Comment by thomasvandoren** [comment]
I haven't merged this yet, because I want to verify it on a few platform. I'm concerned that it may not work on debian platforms that do not have builtin chkconfig support.

**Comment by glaz666** [comment]
Any news on that? Will it be merged?

**Comment by thomasvandoren** [comment]
Sorry for the delay, I'll have some time to go through issues and pull requests this weekend.

**Comment by thomasvandoren** [comment]
Seems to work on ubuntu 12.04 lts.

**Pull request merged**
